---
- name: Zabbix - Add Host
  hosts: localhost
  gather_facts: no
  vars:
    zabbix_force_update: yes
    zabbix_server_url: http://zabbix.knockturn.local/zabbix
    zabbix_user_login: admin
    zabbix_user_pass: zabbix
    zabbix_host_name: test-host2
    zabbix_host_groups: firewalls
    zabbix_host_templates: cisco asa
    zabbix_host_status: enabled
    zabbix_host_state: present
    zabbix_host_int_type: snmp
    zabbix_host_int_address: 8.8.8.8
    zabbix_host_list_port: 161
    zabbix_host_proxy:
  tasks:
  - name: Zabbix - Add Host
    zabbix_host:
      force: '{{ zabbix_force_update }}'
      server_url: '{{ zabbix_server_url }}'
      login_user: '{{ zabbix_user_login }}'
      login_password: '{{ zabbix_user_pass }}'
      host_name: '{{ zabbix_host_name }}'
      host_groups: 
        - '{{ zabbix_host_groups }}'
      link_templates:
        - '{{ zabbix_host_templates }}'
      status: '{{ zabbix_host_status }}'
      state: '{{ zabbix_host_state }}'
      interfaces:
        - type: '{{ zabbix_host_int_type }}'
          main: 1
          useip: 1
          ip: '{{ zabbix_host_int_address }}'
          dns: ""
          port: '{{ zabbix_host_list_port }}'
      proxy: '{{ zabbix_host_proxy|default("") }}'
      validate_certs: false
